#!/bin/env python3
# Created by atbswp (https://github.com/rmpr/atbswp)
# on 28 May 2021 
import pyautogui
import time
pyautogui.FAILSAFE = False

pyautogui.mouseDown(85, 105, 'left')
pyautogui.mouseUp(85, 105, 'left')
time.sleep(2)
pyautogui.mouseDown(86, 107, 'left')
pyautogui.mouseUp(86, 107, 'left')
time.sleep(3)
pyautogui.mouseDown(87, 107, 'left')
pyautogui.mouseUp(87, 107, 'left')
time.sleep(3)
pyautogui.keyDown('altleft')
pyautogui.keyDown('tab')
pyautogui.keyUp('tab')
pyautogui.keyUp('altleft')
time.sleep(1)
pyautogui.moveTo(265, 308)
pyautogui.moveTo(283, 337)
pyautogui.moveTo(296, 362)
pyautogui.moveTo(305, 383)
pyautogui.moveTo(312, 404)
pyautogui.moveTo(323, 425)
pyautogui.moveTo(346, 437)
pyautogui.moveTo(367, 445)