#!/bin/env python3
# Created by atbswp v0.3.0 (https://git.sr.ht/~rmpr/atbswp)
# on 31 May 2021 
import pyautogui
import time
pyautogui.FAILSAFE = True

pyautogui.moveTo(351, 442)
pyautogui.moveTo(303, 406)
pyautogui.moveTo(257, 372)
pyautogui.moveTo(217, 342)
pyautogui.moveTo(190, 323)
pyautogui.moveTo(171, 302)
pyautogui.moveTo(140, 278)
pyautogui.moveTo(118, 263)
pyautogui.moveTo(86, 251)
time.sleep(8)
pyautogui.moveTo(213, 336)
pyautogui.moveTo(242, 357)
pyautogui.moveTo(268, 377)
pyautogui.moveTo(286, 399)