#!/bin/env python3
# Created by atbswp (https://github.com/rmpr/atbswp)
# on 20 Apr 2021 
import pyautogui
import time
pyautogui.FAILSAFE = False

pyautogui.mouseDown(1153, 326, 'left')
pyautogui.mouseUp(1153, 326, 'left')
pyautogui.keyDown('ctrlleft')
pyautogui.keyDown('tab')
pyautogui.keyUp('tab')
pyautogui.keyDown('tab')
pyautogui.keyUp('tab')
pyautogui.keyDown('tab')
pyautogui.keyUp('tab')
pyautogui.keyDown('shift_left')
pyautogui.keyUp('### This key is not supported yet')
pyautogui.keyUp('### This key is not supported yet')
pyautogui.keyUp('### This key is not supported yet')
pyautogui.keyUp('shift_left')
pyautogui.keyUp('ctrlleft')