#!/bin/env python3
# Created by atbswp (https://github.com/rmpr/atbswp)
# on 20 Apr 2021 
import pyautogui
import time
pyautogui.FAILSAFE = False

pyautogui.keyUp('tab')
pyautogui.keyDown('tab')
pyautogui.keyUp('tab')
pyautogui.keyDown('tab')
pyautogui.keyUp('tab')
pyautogui.keyDown('tab')
pyautogui.keyUp('tab')
time.sleep(1)
pyautogui.keyDown('shift_left')
pyautogui.keyUp('### This key is not supported yet')
pyautogui.keyUp('shift_left')
pyautogui.keyUp('altleft')
pyautogui.moveTo(1081, 763)
pyautogui.mouseDown(85, 106, 'left')
pyautogui.mouseUp(85, 106, 'left')
time.sleep(3)
time.sleep(3)
pyautogui.mouseDown(86, 107, 'left')
pyautogui.mouseUp(86, 107, 'left')
time.sleep(3)
pyautogui.keyDown('altleft')
pyautogui.keyDown('tab')
pyautogui.keyUp('tab')
pyautogui.keyUp('altleft')
time.sleep(1)